/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_raindrop_com_test_ScrollViewActivity */

#ifndef _Included_test_raindrop_com_test_ScrollViewActivity
#define _Included_test_raindrop_com_test_ScrollViewActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
